name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x, 1.11.x]
    runs-on: ubuntu-latest

    steps:
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout git repository
        uses: actions/checkout@v2
      - name: build golang
        run: go build
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...
      - name: upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
